# Generated by Django 5.2.5 on 2025-08-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('LPG', 'LPG'), ('PETROL', 'Benzyna'), ('DIESEL', 'Diesel')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
