# Generated by Django 5.2.5 on 2025-09-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'time')},
        ),
    ]
