# Generated by Django 5.2.5 on 2025-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Benzyna'), ('DIESEL', 'Diesel'), ('LPG', 'LPG')], max_length=20),
        ),
    ]
